# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  - name: vault-init
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: hashicorp/vault
      tag: "1.14.0"
      imagePullPolicy: Always
    volumes:
        - name: run-script
          configMap:
            name: run-script
    volumeMounts:
      - mountPath: ./app/run.sh
        subPath: run.sh
        name: run-script
        readOnly: true
    env:
    - name: VAULT_ADDRESS
      value: "http://vault-server:8200"
    - name: VAULT_ROOT_TOKEN
      value: "dev-only-token"
    schedule: "* * * * *"
    args:
        - /bin/sh
        - /app/run.sh
    serviceAccount:
      name: "vault-init"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: Never
    suspend: true