apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicHlhZXBoeW9oZWluLXR3IiwicGFzc3dvcmQiOiJnaHBfMDh6NUdNc2FDY291dVF4S3VvOXdpTG1YSzNLWTQ3MGZrV2JFIiwiZW1haWwiOiJweWFlcGh5by5oZWluQHRoaXRzYXdvcmtzLmNvbSIsImF1dGgiOiJjSGxoWlhCb2VXOW9aV2x1TFhSM09tZG9jRjh3T0hvMVIwMXpZVU5qYjNWMVVYaExkVzg1ZDJsTWJWaExNMHRaTkRjd1ptdFhZa1U9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "lcc.fullname" . }}-pullsecret
type: kubernetes.io/dockerconfigjson